name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  deploy-hmg:
    runs-on: ubuntu-latest
    environment:
      name: hmg
      url: 'https://diegobrittto.com'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy, hmg!

  deploy-drd:
    runs-on: ubuntu-latest
    environment:
      name: drd
      url: 'https://diegobrittto.com'
    needs: deploy-hmg
    steps:
      - name: Run a one-line script
        run: echo Deploy, drd!
