name: CI_TESTE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependências de lint
        run: |
          npm install htmlhint stylelint eslint

      - name: Verificar HTML
        run: npx htmlhint ./index.html

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Simular build (copiar arquivos)
        run: |
          mkdir dist
          cp index.html style.css script.js dist/

  deploy-hmg:
    runs-on: ubuntu-latest
    environment:
      name: hmg
      url: 'https://diegobrittto.com'
    needs: build
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      # Removido o passo de instalação da AWS CLI porque já vem instalada no ubuntu-latest

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2   # Região configurada diretamente aqui

      - name: Subir arquivos para o S3
        run: |
          mkdir dist
          cp index.html style.css script.js dist/
          aws s3 sync dist/ s3://calculadora-devops/ --delete 

  deploy-drd:
    runs-on: ubuntu-latest
    environment:
      name: drd
    needs: build
    steps:
      - name: Exemplo de Deploy DRD
        run: echo Deploy ambiente DRD!
