name: DemoNewCD
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubunto-latest
    steps:
      - name: Run a one-line scripty
        run: echo hello, word!

  deploy-dev:
    runs-on: ubunto-latest
    environment:
      name: dev
      url: 'diegobrittto.com'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy, Dev!

  deploy-hmg:
    runs-on: ubunto-latest
    environment:
      name: hmg
      url: 'diegobrittto.com'
    needs: deploy-dev
    steps:
      - name: Run a one-line scripty
        run: echo Deploy, hmg!

  deploy-drd:
    runs-on: ubunto-latest
    environment:
      name: drd
      url: 'diegobrittto.com'
    needs: deploy-hmg
    steps:
      - name: Run a one-line scripty
        run: echo Deploy, drd!
